config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  root "store#index", as: 'store_index'
  resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  include CurrentCart
  before_action :set_cart
  
  def index
    @products = Product.order(:title)
  end
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/store/_notice.html.erb
<% if notice.present? %>
  <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg
            inline-block" id="notice">
    <%= notice %>
  </p>
<% else %>
  <div id="notice"></div>
<% end %>

app/views/store/index.html.erb
<div class="w-full">
  <%= render 'notice' %>

  <h1 class="font-bold text-xl mb-6 pb-2 border-b-2">Your catalog</h1>
  <ul>
    <% cache @products do %>
    <% @products.each do |product|%>
      <% cache product do %>
      <li class= 'flex mb-6'>
      <%= image_tag(product.image_url, class: 'object-contain w-40 h-48 shadow mr-46')%>
      <div>
        <h2 class="font-bold text-lg mb-3"><%= product.title%></h2>
        <p><%= sanitize(product.description) %></p>
        <div class="mt-3"><%= number_to_currency(product.price)%>
        <%= button_to 'Add to Cart', line_items_path(product_id: product),
            form_class: 'inline',
            class: 'ml-4 rounded-lg py-1 px-2 text-white bg-green-600' %>
        </div>
      </div>
      </li>    
    <% end %>
    <% end %>
    <% end %>
  </ul>
</div>